STAT_KEYS = ["PPG", "RPG", "FGPCT", "THREEPCT", "SPG", "BPG", "DRPG"]
TEAM_NAMES = []
ABV_TO_NAME = {
    "ATL": ["Atlanta Hawks", "Hawks"],
    "BOS": ["Boston Celtics", "Celtics"],
    "BKN": ["Brooklyn Nets", "Nets"],
    "CHA": ["Charlotte Hornets", "Hornets"],
    "CHI": ["Chicago Bulls", "Bulls"],
    "CLE": ["Cleveland Cavaliers", "Cavaliers"],
    "DAL": ["Dallas Mavericks", "Mavericks"],
    "DEN": ["Denver Nuggets", "Nuggets"],
    "DET": ["Detroit Pistons", "Pistons"],
    "GSW": ["Golden State Warriors", "Warriors"],
    "HOU": ["Houston Rockets", "Rockets"],
    "IND": ["Indiana Pacers", "Pacers"],
    "LAC": ["Los Angeles Clippers", "LA Clippers", "Clippers"],
    "LAL": ["Los Angeles Lakers", "LA Lakers", "Lakers"],
    "MEM": ["Memphis Grizzlies", "Grizzlies"],
    "MIA": ["Miami Heat", "Heat"],
    "MIL": ["Milwaukee Bucks", "Bucks"],
    "MIN": ["Minnesota Timberwolves", "Timberwolves"],
    "NOP": ["New Orleans Pelicans", "Pelicans"],
    "NYK": ["New York Knicks", "Knicks"],
    "OKC": ["Oklahoma City Thunder", "Thunder"],
    "ORL": ["Orlando Magic", "Magic"],
    "PHI": ["Philadelphia 76ers", "Philadelphia Sixers", "76ers", "Sixers"],
    "PHX": ["Phoenix Suns", "Suns"],
    "POR": ["Portland Trail Blazers", "Trail Blazers"],
    "SAC": ["Sacramento Kings", "Kings"],
    "SAS": ["San Antonio Spurs", "Spurs"],
    "TOR": ["Toronto Raptors", "Raptors"],
    "UTA": ["Utah Jazz", "Jazz"],
    "WAS": ["Washington Wizards", "Wizards"]
}